.TH DM "1" "February 2010" "ds" "Display Starter"
.SH NAME
ds \- manual page for ds display starter
.SH SYNOPSIS
.B ds
user
.SH DESCRIPTION
.B ds
is a simple and efficient display starter.
.PP
It starts the X server and logs into as given user then runs the script at ~/.xinitrc with the
users login shell.
.PP
.B ds
will respond to the TERM and INT signals. If one of these signals is received, ds forwards it to the 
process running the .xinitrc
.SH AUTHOR
Originally written by Quentin Carbonneaux but heavily modified by Mytchel Hammond
.SH COPYRIGHT
.br
See the LICENSE file distributed in the package for details.
